[package]
name = "experimental-jpeg-rewrite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive"] }
image = { version = "0.24.5", default-features = false, features = ["jpeg_rayon"] }
walkdir = "2.3.2"
